Fix transport endpoint issue for rclone mounter
IBM/ibm-object-csi-driver-operator pull request #12
Opened 2024-04-08 12:44 UTC by Bhagyashreek8

2024-04-08 12:45 UTC, Bhagyashreek8 commented
Test results added in GHE - https://github.ibm.com/alchemy-containers/armada-storage/issues/5726#issuecomment-76658239

2024-04-08 13:50 UTC, Bhagyashreek8 commented
UT test results
```
$ go test -v -coverpkg=./... -coverprofile=profile.cov ./... && cat profile.cov | grep -v /controllers/fake/ | grep -v /api/ > profile2.cov && go tool cover -func profile2.cov
?   	github.com/IBM/ibm-object-csi-driver-operator	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/api/v1alpha1	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_create	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_delete	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_get	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_get/csidriver	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_get/pvc	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_get/serviceaccount	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_get/deployment	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_list	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_list/nodeserverpod	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_update	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/fake/client_update/ibmobjectcsi	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/internal/common	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/internal/crutils	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/syncer	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/util	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/controllers/util/common	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/pkg/config	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/pkg/util/boolptr	[no test files]
?   	github.com/IBM/ibm-object-csi-driver-operator/version	[no test files]
=== RUN   TestIBMObjectCSIReconcile
=== RUN   TestIBMObjectCSIReconcile/Positive:_Successful
=== RUN   TestIBMObjectCSIReconcile/Positive:_IBMObjectCSI_CR_not_found
=== RUN   TestIBMObjectCSIReconcile/Positive:_Sync_controller_deployment_&_pod_containers_and_update_status_in_IBMObjectCSI_CR
=== RUN   TestIBMObjectCSIReconcile/Positive:_Successfully_updated_status_in_IBMObjectCSI_CR_after_validating_if_pod_images_are_in_sync
=== RUN   TestIBMObjectCSIReconcile/Positive:_Successfully_removed_finaliser_from_IBMObjectCSI_CR
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_get_IBMObjectCSI_CR
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_Add_Finalizer_in_IBMObjectCSI_CR
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_create_CSI_driver_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_get_CSI_driver_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_create_service_account_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Failed_to_get_node_daemon_set_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Failed_to_get_controller_deployment_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_restart_node_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Failed_to_get_service_account_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_get_controller_pod_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Controller_pod_not_found_while_reconciling
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_sync_CSI_Controller
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_sync_CSI_Node
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_update_status_in_IBMObjectCSI_CR
=== RUN   TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_cluster_role_binding
=== RUN   TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_cluster_role
=== RUN   TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_storage_class
=== RUN   TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_CSI_driver
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_get_CSI_driver_while_deleting
=== RUN   TestIBMObjectCSIReconcile/Negative:_Failed_to_remove_finaliser_from_IBMObjectCSI_CR
--- PASS: TestIBMObjectCSIReconcile (0.02s)
    --- PASS: TestIBMObjectCSIReconcile/Positive:_Successful (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Positive:_IBMObjectCSI_CR_not_found (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Positive:_Sync_controller_deployment_&_pod_containers_and_update_status_in_IBMObjectCSI_CR (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Positive:_Successfully_updated_status_in_IBMObjectCSI_CR_after_validating_if_pod_images_are_in_sync (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Positive:_Successfully_removed_finaliser_from_IBMObjectCSI_CR (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_get_IBMObjectCSI_CR (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_Add_Finalizer_in_IBMObjectCSI_CR (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_create_CSI_driver_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_get_CSI_driver_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_create_service_account_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Failed_to_get_node_daemon_set_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Failed_to_get_controller_deployment_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_restart_node_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Failed_to_get_service_account_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_get_controller_pod_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Controller_pod_not_found_while_reconciling (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_sync_CSI_Controller (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_sync_CSI_Node (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_update_status_in_IBMObjectCSI_CR (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_cluster_role_binding (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_cluster_role (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_storage_class (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_IBMObjectCSI_CR_is_deleted_and_failed_to_delete_CSI_driver (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_get_CSI_driver_while_deleting (0.00s)
    --- PASS: TestIBMObjectCSIReconcile/Negative:_Failed_to_remove_finaliser_from_IBMObjectCSI_CR (0.00s)
=== RUN   TestIBMObjectCSISetupWithManager
=== RUN   TestIBMObjectCSISetupWithManager/Positive:_Successful
--- PASS: TestIBMObjectCSISetupWithManager (0.00s)
    --- PASS: TestIBMObjectCSISetupWithManager/Positive:_Successful (0.00s)
=== RUN   TestRecoverStaleVolumeReconcile
=== RUN   TestRecoverStaleVolumeReconcile/Positive:_Successful
=== RUN   TestRecoverStaleVolumeReconcile/Positive:_RecoverStaleVolume_CR_not_found
=== RUN   TestRecoverStaleVolumeReconcile/Positive:_No_workload_is_passed_to_watch
=== RUN   TestRecoverStaleVolumeReconcile/Positive:_Node_Server_Pods_not_found
=== RUN   TestRecoverStaleVolumeReconcile/Negative:_Failed_to_get_RecoverStaleVolume_CR
=== RUN   TestRecoverStaleVolumeReconcile/Negative:_Deployment_Name_is_missing
=== RUN   TestRecoverStaleVolumeReconcile/Negative:_Failed_to_get_deployment
=== RUN   Tes [...]

2024-04-17 16:27 UTC, ashimagarg27 requested changes
Changes looks good, added minor review suggestions, ptal.

2024-04-17 16:27 UTC, ashimagarg27 commented on api/v1alpha1/ibmobjectcsi_types.go
> +	Resources ResourcesSpec `json:"resources,omitempty"`
Why we need resources at IBMObject CSI CR level?

2024-04-17 16:27 UTC, ashimagarg27 commented on controllers/internal/crutils/ibmobjectcsi.go
> +}
Is this method getting used anywhere?

2024-04-17 16:27 UTC, ashimagarg27 commented on controllers/syncer/csi_node.go
> +		//Resources:    ensureDefaultResources(),
Please remove the commented code and I guess after this PR, method `ensureDefaultResources()` has become unused, please confirm and do cleanup accordingly

2024-04-18 09:45 UTC, nkkashyap approved these changes
lgtm remove `ensureDefaultResources` as it is not used any more

2024-04-18 12:49 UTC, ashimagarg27 approved these changes
PR looks good!!

2024-04-18 12:55 UTC, merged