Domain and Group change <WIP>
IBM/ibm-object-csi-driver-operator pull request #5
Opened 2024-02-29 12:08 UTC by ambiknai

2024-02-29 14:03 UTC, ashimagarg27 requested changes

2024-02-29 14:03 UTC, ashimagarg27 commented on controllers/recoverstalevolume_controller.go
>  	csiv1alpha1 "github.ibm.com/alchemy-containers/ibm-object-csi-driver-operator/api/v1alpha1"
`csiv1alpha1` => `objectdriverv1alpha1`

2024-03-01 08:54 UTC, ashimagarg27 approved these changes

2024-03-01 09:02 UTC, nkkashyap approved these changes
lgtm

2024-03-01 09:09 UTC, merged